// Generated by CoffeeScript 1.10.0
(function() {
  var $order_form, CityField, city, orderFormSubmit;

  CityField = (function() {
    CityField.kladr = [];

    CityField.variantsDelivery = {
      'courier': false,
      'points': false
    };

    CityField.variantsDeliveryPost = {
      'err': true
    };

    CityField.maxTotalPrice = 5000;

    CityField.requestStatus = 0;

    CityField.margin = 0;

    CityField.countRequestForMargin = 0;

    function CityField() {
      CityField.kladr_key = '97d13f084f24de48a7a6311259b40518';
      CityField.kladr_token = 'db2ef881e129cd5dd73b362a307f1d10';
      CityField.kladr_limit = 5;
      CityField.field_id = "#" + 'shipping_address_city';
      CityField.id_delivery_courier = 415531;
      CityField.id_delivery_points = 415532;
      CityField.id_delivery_point_description = 3224898;
      CityField.id_delivery_post_calc = 435233;
      CityField.id_payment = 344685;
      CityField.id_payment_postcalc = 359944;
      CityField.id_payment_online = 310842;
      CityField.id_payment_online_2 = 364405;
      CityField.id_payment_rko = 3247644;
      $(CityField.field_id).parent().append('<div class="address__autocomplete"></div>');
      CityField.autocompleteBlock = $('.address__autocomplete');
      CityField.limitDefault = 15000;
      CityField.limit = CityField.limitDefault;
    }


    /**
     * Метод инициализации поля ввода города
     */

    CityField.prototype.init = function() {
      CityField.limiter();
      $('#payment_gateways').append('<div class="total_price"><p class="fl">Итого:</p><p class="fr price prices-current"></p></div>');
      $('.delivery_variants').addClass('loader');
      if ($('.delivery_variants tbody .load').length === 0) {
        $('.delivery_variants tbody').append('<tr class="load"><td></td></tr>');
      }
      $('.payment_variants').addClass('loader');
      if ($('.payment_variants tbody .load').length === 0) {
        $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
      }
      $('#order_payment_gateway_id_' + CityField.id_payment_online_2).parent().parent().hide();
      $('input[type="submit"]').hide();
      console.log('zip object ' + $('#shipping_address_zip').length);
      if ($('#shipping_address_zip').length > 0) {
        console.log('check zip');
        $('#shipping_address_zip').bind('blur', function() {
          console.log('check zip blur');
          if (CityField.requestStatus === 1 && $('#shipping_address_zip').attr('data-value') !== $('#shipping_address_zip').val() && $('#shipping_address_zip').val().length > 0) {
            $('#shipping_address_zip').attr('data-value', $('#shipping_address_zip').val());
            return CityField.getDelivery();
          }
        });
        $('#shipping_address_zip').bind('keydown', function(e) {
          if (e.keyCode === 13) {
            console.log('check zip ENTER');
            if (CityField.requestStatus === 1 && $('#shipping_address_zip').attr('data-value') !== $('#shipping_address_zip').val() && $('#shipping_address_zip').val().length > 0) {
              $('#shipping_address_zip').attr('data-value', $('#shipping_address_zip').val());
              return CityField.getDelivery();
            }
          }
        });
      }
      $(CityField.field_id).attr('autocomplete', 'off');
      if ($(CityField.field_id).val().length === 0 || !Cookies.get('customstreetwear_kladr_city')) {
        CityField.geoIp();
      } else {
        CityField.getProductsAndSales(CityField.getDelivery);
      }
      $(CityField.field_id).bind('blur', function() {
        if (CityField.autocompleteBlock.css('display') === 'block') {
          return setTimeout(function() {
            if ($('.address__autocomplete__item--selected').length > 0) {
              $('.address__autocomplete__item--selected').click();
            } else {
              $('.address__autocomplete__item').eq(0).click();
            }
            if ($(CityField.field_id).val() === '') {
              CityField.kladr['city'] = '';
              CityField.kladr['city_kladr'] = '';
              CityField.kladr['index'] = '';
              CityField.kladr['region'] = '';
              CityField.kladr['code'] = '';
            }
            if ($('.address__autocomplete div').length === 0) {
              CityField.kladr['city'] = $(CityField.field_id).val();
              CityField.kladr['city_kladr'] = $(CityField.field_id).val();
              CityField.kladr['index'] = '';
              CityField.kladr['region'] = $(CityField.field_id).val();
              CityField.kladr['code'] = '';
            }
            return CityField.getProductsAndSales(CityField.getDelivery);
          }, 300);
        }
      });
      $(CityField.field_id).bind('keydown', function(e) {
        if (e.keyCode === 13) {
          return CityField.getProductsAndSales(CityField.getDelivery);
        }
      });
      return $(CityField.field_id).bind('keyup', function(e) {
        return CityField.getKladr();
      });
    };


    /**
     * Вычисление итоговой стоимости
     */

    CityField.calcTotal = function() {
      var delivery_price, rel_price, result, salePrice, salePriceOnline, total_price, total_price_cart;
      total_price_cart = parseInt(CityField.order.total_price);
      rel_price = $('.delivery_variants tr.select input[type="radio"]').attr('rel');
      delivery_price = parseInt($(rel_price).attr('data-price'));
      salePrice = 0;
      salePriceOnline = 0;
      if (!$('.payment_variants').hasClass('loader')) {
        if (CityField.sales.length > 0) {
          $(CityField.sales).each(function(i, e) {
            return salePrice += Math.abs(parseInt(e.amount));
          });
        }
        if (CityField.maxTotalPrice > CityField.order.total_price && CityField.for_order.payments[CityField.id_payment_online_2] !== void 0 && $('#order_payment_gateway_id_' + CityField.id_payment_online).parent().hasClass('select')) {
          salePriceOnline += Math.abs(Math.floor(parseFloat($('#summ_' + CityField.id_payment_online_2).attr('data-price'))));
        }
      }
      total_price = total_price_cart + delivery_price;
      result = {
        delivery_price: delivery_price,
        total_price_cart: total_price_cart,
        total_sale_price: salePrice + salePriceOnline,
        sale_price: salePrice,
        sale_price_online: salePriceOnline,
        total_price: total_price
      };
      return result;
    };


    /**
     * Скрытие способов доставки при превышении максимальной стоимости
     */

    CityField.checkMaxTotalPrice = function() {
      if (CityField.order.total_price > CityField.maxTotalPrice) {
        $('#order_payment_gateway_id_' + CityField.id_payment).parent().parent().remove();
        $('#order_payment_gateway_id_' + CityField.id_payment_postcalc).parent().parent().remove();
      }
      return true;
    };


    /**
     * Получение ip клиента
     */

    CityField.getIp = function() {
      var ip;
      ip = Cookies.get('customstreetwear_ip');
      if (!ip) {
        $.post('http://82.196.3.195:8008/ip.php', function(response) {
          var d;
          d = new Date(new Date().getTime() + 60 * 60 * 1000);
          Cookies.set('customstreetwear_ip', response, {
            expires: d.toUTCString()
          });
          return ip = response;
        });
      }
      return ip;
    };


    /**
     * Получение индексов кладра для города
     */

    CityField.getIndexKladr = function(geoData) {
      var cid, cindex, cityName, getZipForCity, getZipForCityId, getZipForRegion, paramCity, regionName, rid;
      cityName = geoData['city']['name_ru'];
      regionName = geoData['region']['name_ru'];
      cid = null;
      cindex = null;
      rid = null;
      paramCity = {
        'key': this.kladr_key,
        'token': this.kladr_token,
        'limit': this.kladr_limit,
        'query': cityName,
        'contentType': 'city',
        'limit': 1
      };
      getZipForRegion = function() {
        return $.ajax({
          'url': 'http://kladr-api.ru/api.php',
          dataType: "jsonp",
          'data': {
            'key': this.kladr_key,
            'token': this.kladr_token,
            'limit': this.kladr_limit,
            'query': regionName,
            'contentType': 'region',
            'limit': 1
          },
          success: function(response) {
            if (response.result[0]['id']) {
              rid = response.result[0]['id'];
              return getZipForCity();
            }
          }
        });
      };
      getZipForCity = function() {
        if (rid) {
          paramCity['regionId'] = rid;
        } else {
          return;
        }
        return $.ajax({
          'url': 'http://kladr-api.ru/api.php',
          dataType: "jsonp",
          'data': paramCity,
          success: function(response) {
            if (response.result[0]['id']) {
              cid = response.result[0]['id'];
              cindex = response.result[0]['zip'];
              if (!cid) {
                return;
              }
              geoData['region']['id'] = rid;
              geoData['city']['id'] = cid;
              geoData['city']['index'] = cindex;
              return getZipForCityId();
            }
          }
        });
      };
      getZipForCityId = function() {
        var street;
        if (cindex === null) {
          street = null;
          return $.ajax({
            'url': 'http://kladr-api.ru/api.php',
            dataType: "jsonp",
            'data': {
              'key': this.kladr_key,
              'token': this.kladr_token,
              'limit': this.kladr_limit,
              'query': '',
              'contentType': 'street',
              'cityId': cid,
              'limit': 1
            },
            success: function(response) {
              var sid;
              street = response;
              if (!street['result'] || !street['result'][0]) {
                return null;
              }
              if (street['result'][0]['zip'] !== null) {
                return geoData['city']['index'] = street['result'][0]['zip'];
              } else {
                sid = street['result'][0]['id'];
                return $.ajax({
                  'url': 'http://kladr-api.ru/api.php',
                  dataType: "jsonp",
                  'data': {
                    'key': this.kladr_key,
                    'token': this.kladr_token,
                    'limit': this.kladr_limit,
                    'query': '',
                    'contentType': 'building',
                    'streetId': sid,
                    'limit': 1
                  },
                  success: function(response) {
                    street = response;
                    if (street['result'][0]['zip']) {
                      geoData['city']['index'] = street['result'][0]['zip'];
                      return geoData;
                    } else {

                    }
                    return null;
                  }
                });
              }
            }
          });
        }
      };
      getZipForRegion();
      return geoData;
    };


    /**
     * Определение местоположения клиента по IP
     */

    CityField.geoIp = function() {
      var geoIp, updateCityField;
      updateCityField = function(geoIp) {
        $(CityField.field_id)[0].value = geoIp['city']['name_ru'];
        CityField.kladr['city'] = geoIp['city']['name_ru'];
        CityField.kladr['city_kladr'] = geoIp['city']['name_ru'];
        CityField.kladr['index'] = geoIp['city']['ind'];
        CityField.kladr['region'] = geoIp['region']['name_ru'];
        CityField.kladr['kladr_code'] = geoIp['city']['index'];
        return CityField.getProductsAndSales(CityField.getDelivery);
      };
      if (!Cookies.get('customstreetwear_geoip')) {
        $.post('http://82.196.3.195:8008/ip.php', function(response) {
          return $.get('http://ru2.sxgeo.city/8SANV/json/' + response, function(response) {
            var d, geoIp;
            geoIp = response;
            if (geoIp) {
              geoIp = CityField.getIndexKladr(geoIp);
            }
            if (geoIp) {
              d = new Date(new Date().getTime() + 60 * 60 * 1000);
              Cookies.set('customstreetwear_geoip', JSON.stringify(geoIp), {
                expires: d.toUTCString()
              });
            }
            return updateCityField(geoIp);
          });
        });
      } else {
        geoIp = JSON.parse(Cookies.get('customstreetwear_geoip'));
        updateCityField(geoIp);
      }
      if (geoIp && geoIp['country']['name_en'].toLowerCase() !== 'russia') {
        return null;
      }
    };


    /**
     * Получение списка товаров и скидок в корзине
     */

    CityField.getProductsAndSales = function(callback) {
      var cartOrderFormCookie, getSalesAndOrder, order;
      $('#delivery_variants .message_delivery').remove();
      $('.delivery_variants').show();
      $('.delivery_variants').addClass('loader');
      if ($('.delivery_variants tbody .load').length === 0) {
        $('.delivery_variants tbody').append('<tr class="load"><td></td></tr>');
      }
      $('input[type="submit"]').hide();
      getSalesAndOrder = function(order) {
        CityField.order = order;
        CityField.quantity_products = 0;
        CityField.products = CityField.order.order_lines;
        $.each(CityField.products, function(index, item) {
          return CityField.quantity_products += parseInt(item.quantity);
        });
        CityField.sales = CityField.order.discounts;
        if (!$('.set-list').hasClass('set-list-item-ready')) {
          $('.set-list-item').each(function(i, e) {
            return $.each(CityField.products, function(index, item) {
              var html, size;
              html = $(e).find('.description p').html();
              if (i === index) {
                console.log(html.match(CityField.products[index].title));
                size = 'Размер ' + html.substr(CityField.products[index].title.indexOf('('), CityField.products[index].title.length).replace(/\(|\)/g, '');
                $(e).find('.description p:first-child').html(CityField.products[index].title);
                $(e).find('.description p:last-child').html(size + ', <span>' + $(e).find('.description p:last-child').html() + '</span>');
                return $(e).find('.description p:first-child').after('<p>' + CityField.products[index].comment.substr(0, CityField.products[index].comment.indexOf(',')) + '</p>');
              }
            });
          });
          $('.set-list').addClass('set-list-item-ready');
          $('.set-list-item .description').css('opacity', 1);
        }
        CityField.checkMaxTotalPrice();
        return callback();
      };
      cartOrderFormCookie = Cookies.get('cart_order_form');
      if (cartOrderFormCookie) {
        order = JSON.parse(cartOrderFormCookie);
        getSalesAndOrder(order);
      } else {
        $.getJSON('/cart_items_with_accessories.json', function(order) {
          return getSalesAndOrder(order);
        }).fail(function() {
          return CityField.getProductsAndSales(callback);
        });
      }
    };


    /**
     * Получение списка городов из kladr
     */

    CityField.getKladr = function() {
      var query;
      query = $(this.field_id).val().replace("ё", "е");
      CityField.clearKladr();
      CityField.autocompleteBlock.removeClass('trans');
      return $.ajax({
        'url': 'http://kladr-api.ru/api.php',
        dataType: "jsonp",
        'data': {
          'key': this.kladr_key,
          'token': this.kladr_token,
          'limit': this.kladr_limit,
          'query': query,
          'contentType': 'city',
          'withParent': 1
        },
        success: function(response) {
          var html;
          html = CityField.buildVariants(response.result, query, response.searchContext);
          CityField.autocompleteBlock.show();
          CityField.autocompleteBlock.html(html);
          if (CityField.autocompleteBlock.find('*').length === 0) {
            CityField.autocompleteBlock.addClass('trans');
          }
          return CityField.clickAutocompleteItem();
        }
      });
    };


    /**
     * Вывод скидки в сайдбаре
     */

    CityField.setSaleSidebar = function() {
      var prices, total_price_view;
      prices = CityField.calcTotal();
      if ($('.set-sidebar .set-meta-custom').length > 0) {
        $('.set-sidebar .set-meta-custom').remove();
      }
      total_price_view = '<div class="fc b"><p class="fl">Итого:</p><p class="fr prices-current">' + prices.total_price + ' руб.</p></div>';
      if (prices.total_sale_price > 0 || prices.delivery_price > 0) {
        $('.set-sidebar').append('<div class="set-meta set-meta-custom"></div>');
        if (prices.total_sale_price > 0) {
          $('.set-sidebar .set-meta-custom').append('<div class="fc meta_sale"><p class="fl">Скидка:</p><p class="fr prices-current">-' + prices.total_sale_price + ' руб.</p></div>');
          total_price_view = '<div class="fc b prices-sale"><p class="fl">Итого:</p><p class="fr prices-current"><span>' + (prices.total_price + prices.sale_price) + ' руб.</span>' + (prices.total_price - prices.sale_price_online) + ' руб.</p></div>';
        }
        if (prices.delivery_price > 0) {
          $('.set-sidebar .set-meta-custom').append('<div class="fc"><p class="fl">Доставка:</p><p class="fr prices-current">' + prices.delivery_price + ' руб.</p></div>');
        }
      }
      return $('.set-sidebar .set-meta-custom').append(total_price_view);
    };


    /**
     * Получение данных о доставке
     */

    CityField.getDelivery = function() {
      var callbackDelivery, getMargin, index, params;
      CityField.limit = CityField.limitDefault;
      CityField.limiter();
      index = CityField.kladr['index'] ? CityField.kladr['index'] : Cookies.get('customstreetwear_kladr_index');
      if ($('#shipping_address_zip').val().length > 0) {
        index = parseInt($('#shipping_address_zip').val());
      }
      params = {
        city: $.trim(CityField.kladr['city'] ? CityField.kladr['city'] : Cookies.get('customstreetwear_kladr_city')).replace('г. ', ''),
        city_kladr: $.trim(CityField.kladr['city_kladr'] ? CityField.kladr['city_kladr'] : Cookies.get('customstreetwear_kladr_city_kladr')).replace('г. ', ''),
        index: index,
        region: $.trim(CityField.kladr['region'] ? CityField.kladr['region'] : Cookies.get('customstreetwear_kladr_region')),
        kladr_code: $.trim(CityField.kladr['kladr_code'] ? CityField.kladr['kladr_code'] : Cookies.get('customstreetwear_kladr_code')),
        products: JSON.stringify(CityField.products),
        sales: JSON.stringify(CityField.sales)
      };
      $('.rko').remove();
      CityField.requestStatus = 0;
      $('#delivery_variants .message_delivery').remove();
      $('.delivery_variants').show();
      $('.delivery_variants').addClass('loader');
      if ($('.delivery_variants tbody .load').length === 0) {
        $('.delivery_variants tbody').append('<tr class="load"><td></td></tr>');
      }
      $('.payment_variants').addClass('loader');
      if ($('.payment_variants tbody .load').length === 0) {
        $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
      }
      $(this.field_id).prop('disabled', true);
      $('#order_delivery_variant_id_' + CityField.id_delivery_courier).parent().parent().hide();
      $('#order_delivery_variant_id_' + CityField.id_delivery_points).parent().parent().hide();
      $('#order_delivery_variant_id_' + CityField.id_delivery_post_calc).parent().parent().hide();
      if (!CityField.kladr['region']) {
        CityField.kladr['region'] = CityField.kladr['city_kladr'];
      }
      getMargin = function() {
        return $.ajax({
          url: '/payment/for_order.json',
          type: 'PUT',
          dataType: 'json',
          data: $('#order_form').serialize(),
          timeout: 10000,
          success: function(data) {
            CityField.countRequestForMargin++;
            CityField.for_order = data;
            if (data.payments[CityField.id_payment_online_2] !== void 0 || CityField.countRequestForMargin > 2) {
              if (data.payments[CityField.id_payment_online_2] !== void 0) {
                CityField.margin = Math.abs(parseInt(data.payments[CityField.id_payment_online_2].margin));
              }
              CityField.countRequestForMargin = 0;
              return callbackDelivery();
            } else {
              return getMargin();
            }
          }
        });
      };
      getMargin();
      callbackDelivery = function() {
        return $.post('http://82.196.3.195:8008/delivery.php', params, function(response) {
          $(CityField.field_id).prop("disabled", false);
          CityField.variantsDelivery = response;
          $('.delivery_info').remove();
          $.post('http://82.196.3.195:8008/postcalc.php', params, function(response) {
            $(CityField.field_id).prop("disabled", false);
            CityField.variantsDeliveryPost = response;
            CityField.requestStatus = 1;
            if (CityField.order.total_price <= CityField.maxTotalPrice) {
              CityField.setSaleForOnlinePay();
            } else {
              CityField.changeVariantsDeliveryPostcalc();
              CityField.changeVariantsDelivery();
            }
            $('input[type="submit"]').show();
          }, 'JSON');
        }, 'JSON');
      };
    };


    /**
     * Установка РКО
     */

    CityField.setRKO = function(rko, rko_class) {
      console.log('setRKO' + rko + $('#order_payment_gateway_id_' + CityField.id_payment_postcalc).parent().parent().css('display'));
      $('#payment_gateways .rko').remove();
      if (CityField.maxTotalPrice > CityField.order.total_price) {
        $('#payment_gateways').append('<div class="rko ' + rko_class + '"></div>');
        return $('#payment_gateways .' + rko_class).html('+ ' + rko + ' руб');
      }
    };


    /**
     * Вывод сообщения о невозможности посчитать доставку
     */

    CityField.outputMessageDelivery = function() {
      $('#delivery_variants .message_delivery').remove();
      $('#delivery_variants').append('<div class="message_delivery">Не удалось посчитать доставку, будет рассчитано оператором при подтверждении заказа.</div>');
      return $('.delivery_variants').hide();
    };


    /**
     * Проверка способов доставки, если нет, то выводим сообщение
     */

    CityField.checkEnableDelivery = function() {
      var countVisible;
      console.log('checkEnableDelivery' + CityField.limit);
      if (CityField.limit !== -1) {
        countVisible = 0;
        $('#delivery_variants tr').each(function(i, e) {
          if ($(e).css('display') === 'none') {
            return countVisible++;
          }
        });
        if ($('#delivery_variants tr:not(.not_available)').length === 0 || $('#delivery_variants tr').length === countVisible) {
          CityField.outputMessageDelivery();
          $('#order_field_' + CityField.id_delivery_point_description).val('');
          return $('.set-sidebar .fc.b p.fl').text('Итого:');
        } else {
          $('#delivery_variants .message_delivery').remove();
          $('.set-sidebar .fc.b p.fl').text('Итого:');
          $('.delivery_variants').show();
          $('.payment_variants').addClass('loader');
          if ($('.payment_variants tbody .load').length === 0) {
            return $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
          }
        }
      }
    };


    /**
     * Установка скидки на оплату онлайн
     */

    CityField.setSaleForOnlinePay = function() {
      console.log('setSale = ');
      CityField.changeVariantsDeliveryPostcalc(true);
      return CityField.changeVariantsDelivery(true);
    };


    /**
     * Вывод срока доставки
     */

    CityField.printEstimate = function(min, max) {
      var estimate;
      estimate = '';
      if (min) {
        estimate += min;
      }
      if (max) {
        estimate += '-' + max + ' ' + CityField.dayText(max);
      } else {
        estimate += ' ' + CityField.dayText(min);
      }
      return estimate;
    };


    /**
     * Выбор варианта доставки (почта россии)
     */

    CityField.changeVariantsDeliveryPostcalc = function(rko) {
      var delivery, deliveryType, estimate, id_delivery_post_calc;
      rko = rko || 0;
      id_delivery_post_calc = CityField.id_delivery_post_calc;
      if (CityField.variantsDeliveryPost.err) {
        delivery = {
          "id": id_delivery_post_calc,
          "available": true,
          "active": true,
          "html_id": null,
          "price": null,
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": null,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        $('#order_delivery_variant_id_' + id_delivery_post_calc).trigger('update:insales:delivery', delivery);
        $('#order_delivery_variant_id_' + id_delivery_post_calc).trigger('disable:insales:delivery');
        $('#order_delivery_variant_id_' + id_delivery_post_calc).parent().parent().hide();
        $('.delivery_variants tr:nth-child(3)').find('small').empty();
        return $('#payment_gateways .rko_post').remove();
      } else {
        deliveryType = CityField.variantsDeliveryPost.deliveryType;
        estimate = CityField.variantsDeliveryPost.estimate + ' ' + CityField.dayText(parseInt(CityField.variantsDeliveryPost.estimate));
        $('.delivery_variants tr:nth-child(3)').show();
        $('.delivery_variants tr:nth-child(3)').find('.price > span').addClass('show');
        setTimeout(function() {
          if (!CityField.variantsDelivery.courier && !CityField.variantsDelivery.points) {
            $('.delivery_variants tr:nth-child(3)').find('input[type="radio"]').click();
            return $('.delivery_variants tr:nth-child(3)').find('input[type="radio"]').trigger('enable:insales:delivery');
          }
        }, 2000);
        $('.delivery_variants tr:nth-child(3)').find('input[type="radio"]').click(function() {
          var descriptionDeliveryPost;
          CityField.checkPaymentMethods();
          descriptionDeliveryPost = 'Почта России ' + CityField.variantsDeliveryPost.deliveryType;
          return $('#order_field_' + CityField.id_delivery_point_description).val(descriptionDeliveryPost);
        });
        delivery = {
          "id": id_delivery_post_calc,
          "available": true,
          "active": true,
          "html_id": '#order_delivery_variant_id_' + id_delivery_post_calc,
          "price": CityField.variantsDeliveryPost.totalCost,
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": deliveryType + '<br/>' + estimate,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        return $('#order_delivery_variant_id_' + id_delivery_post_calc).trigger('update:insales:delivery', delivery);
      }
    };


    /**
     * Склонение дней
     */

    CityField.dayText = function(day, type) {
      var declOfNum;
      type = type || 0;
      declOfNum = function(number, titles) {
        var cases;
        cases = [2, 0, 1, 1, 1, 2];
        return titles[number % 100 > 4 && number % 100 < 20 ? 2 : cases[number % 10 < 5 ? number % 10 : 5]];
      };
      if (type) {
        return declOfNum(day, ['рабочего дня', 'рабочих дней', 'рабочих дней']);
      } else {
        return declOfNum(day, ['рабочий день', 'рабочих дня', 'рабочих дней']);
      }
    };


    /**
     * Выбор варианта доставки (курьер или пункт выдачи)
     */

    CityField.changeVariantsDelivery = function(rko) {
      var arrayPrices, arrayRKO, delivery, estimate, id_delivery_courier, id_delivery_points, partner, price;
      rko = rko || false;
      $('.delivery_variants script').remove();
      id_delivery_courier = CityField.id_delivery_courier;
      id_delivery_points = CityField.id_delivery_points;
      if (!CityField.variantsDelivery.courier) {
        delivery = {
          "id": id_delivery_courier,
          "available": true,
          "active": true,
          "html_id": null,
          "price": null,
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": null,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        $('#order_delivery_variant_id_' + id_delivery_courier).trigger('update:insales:delivery', delivery);
        $('#order_delivery_variant_id_' + id_delivery_courier).trigger('disable:insales:delivery');
        $('#order_delivery_variant_id_' + id_delivery_courier).parent().parent().hide();
        $('.delivery_variants tr:nth-child(1)').find('.name > div').empty().removeClass('show');
        $('.delivery_variants tr:nth-child(1)').find('small').empty();
        $('#payment_gateways .rko_courier').remove();
      } else {
        partner = 'Служба доставки ' + CityField.variantsDelivery.courier.parnter_name;
        estimate = '';
        if (CityField.variantsDelivery.courier.min_estimate) {
          estimate += CityField.variantsDelivery.courier.min_estimate;
        }
        if (CityField.variantsDelivery.courier.max_estimate) {
          estimate += '-' + CityField.variantsDelivery.courier.max_estimate;
          estimate += ' ' + CityField.dayText(CityField.variantsDelivery.courier.max_estimate);
        } else {
          estimate += ' ' + CityField.dayText(CityField.variantsDelivery.courier.min_estimate);
        }
        $('.delivery_variants tr:nth-child(1)').show();
        $('.delivery_variants tr:nth-child(1)').find('.name > div').eq(0).hide();
        $('.delivery_variants tr:nth-child(1)').find('.price > span').addClass('show');
        $('.delivery_variants tr:nth-child(1)').find('input[type="radio"]').click();
        $('.delivery_variants tr:nth-child(1)').find('input[type="radio"]').click(function() {
          CityField.checkPaymentMethods();
          return $('#order_field_' + CityField.id_delivery_point_description).val('');
        });
        delivery = {
          "id": id_delivery_courier,
          "available": true,
          "active": true,
          "html_id": '#order_delivery_variant_id_' + id_delivery_courier,
          "price": CityField.variantsDelivery.courier.cost + (rko ? CityField.variantsDelivery.courier.RKO : 0),
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": partner + '<br/>' + estimate,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        $('#order_delivery_variant_id_' + id_delivery_courier).trigger('update:insales:delivery', delivery);
      }
      if (!CityField.variantsDelivery.points) {
        delivery = {
          "id": id_delivery_points,
          "available": true,
          "active": true,
          "html_id": null,
          "price": null,
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": null,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        $('#order_delivery_variant_id_' + id_delivery_points).trigger('update:insales:delivery', delivery);
        $('#order_delivery_variant_id_' + id_delivery_points).trigger('disable:insales:delivery');
        $('#order_delivery_variant_id_' + id_delivery_points).parent().parent().hide();
        $('.delivery_variants tr:nth-child(2)').find('select#pvz').find('option').remove();
        $('.delivery_variants tr:nth-child(2)').find('#my').empty();
        return $('.delivery_variants tr:nth-child(2)').find('small').empty();
      } else {
        if (!CityField.variantsDelivery.courier) {
          $('.delivery_variants tr:nth-child(2)').find('input[type="radio"]').click();
        }
        $('.delivery_variants tr:nth-child(2)').show();
        $('.delivery_variants tr:nth-child(2)').find('input[type="radio"]').click(function() {
          var payment;
          CityField.checkPaymentMethods();
          payment = {
            "id": CityField.id_payment,
            "available": true,
            "active": true,
            "html_id": '#order_payment_gateway_id_' + CityField.id_payment,
            "price": parseInt($('#order_delivery_variant_id_' + CityField.id_delivery_points).parent().parent().find('option:selected').attr('data-rko')),
            "fields_values": [],
            "selected": false,
            "description": null,
            "description_html": null,
            "is_external": false,
            "external_url": null,
            "external_data": {}
          };
          return $('#order_payment_gateway_id_' + CityField.id_payment).trigger('update:insales:payment', payment);
        });
        estimate = 'от  ';
        if (CityField.variantsDelivery.points.min_estimate) {
          estimate += CityField.variantsDelivery.points.min_estimate;
        }
        if (CityField.variantsDelivery.points.max_estimate) {
          estimate += '-' + CityField.variantsDelivery.points.max_estimate;
          estimate += ' ' + CityField.dayText(CityField.variantsDelivery.points.max_estimate, 1);
        } else {
          estimate += ' ' + CityField.dayText(CityField.variantsDelivery.points.min_estimate, 1);
        }
        price = CityField.variantsDelivery.points.cost;
        $('.delivery_variants tr:nth-child(2)').find('.name > div').eq(0).hide();
        $('.delivery_variants tr:nth-child(2)').find('.price > span').addClass('show');
        $('.delivery_variants tr:nth-child(2)').find('select#pvz').find('option').remove();
        $('.delivery_variants tr:nth-child(2)').find('input[type="radio"]').css({
          'cursor': 'pointer',
          'opacity': 1
        });
        $('.delivery_variants tr:nth-child(2)').find('select#pvz').bind('change', function() {
          var $deliveryInfoContainer, $optionSelected, adress, adress1, adress2, deliveryInfoArray, pr;
          $('.payment_variants').addClass('loader');
          if ($('.payment_variants tbody .load').length === 0) {
            $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
          }
          $('.delivery_info').remove();
          $(this).parent().parent().after('<div class="delivery_info"><ul></ul></div>');
          $optionSelected = $(this).find('option:selected');
          $deliveryInfoContainer = $('.delivery_info ul');
          adress = $optionSelected.attr('data-adress');
          adress1 = adress.substr(0, adress.indexOf(',')).toLowerCase();
          adress1 = adress1.split(' ');
          adress1.forEach(function(e, i) {
            return adress1[i] = adress1[i].charAt(0).toUpperCase() + adress1[i].slice(1);
          });
          adress1 = adress1.join(' ');
          adress2 = adress.substr(adress.indexOf(','), adress.length);
          estimate = CityField.printEstimate($optionSelected.attr('data-min-estimate'), $optionSelected.attr('data-max-estimate'));
          $('#delivery_description_' + CityField.id_delivery_point_description).html(estimate);
          deliveryInfoArray = {
            "<div class='head'>Адрес:</div> ": adress1 + adress2,
            "<div class='head'>Телефон:</div> ": $optionSelected.attr('data-phone'),
            "<div class='head'>Время работы:</div> ": $optionSelected.attr('data-workTime')
          };
          $('#order_field_' + CityField.id_delivery_point_description).val('Пункт выдачи ' + $optionSelected.val());
          Object.keys(deliveryInfoArray).forEach(function(item, i) {
            return $deliveryInfoContainer.append('<li>' + item + " " + deliveryInfoArray[item] + '</li>');
          });
          $('.delivery_variants tr:nth-child(2)').find('input[type="radio"]').click();
          pr = $(this).find('option:selected').attr('data-price');
          $('#delivery_price').empty().append(pr + ' руб.');
          $('*[name="order[delivery_price]"]').val(pr);
          delivery = {
            "id": id_delivery_points,
            "available": true,
            "active": true,
            "html_id": '#order_delivery_variant_id_' + id_delivery_points,
            "price": parseInt(pr) + parseInt(rko ? $(this).find('option:selected').attr('data-rko') : 0),
            "fields_values": [],
            "selected": false,
            "description": null,
            "description_html": estimate,
            "is_external": false,
            "external_url": null,
            "external_data": {}
          };
          return $('#order_delivery_variant_id_' + id_delivery_points).trigger('update:insales:delivery', delivery);
        });
        arrayPrices = Object.keys(CityField.variantsDelivery.points.list).map(function(key) {
          return CityField.variantsDelivery.points.list[key].price;
        });
        if (rko) {
          arrayRKO = Object.keys(CityField.variantsDelivery.points.list).map(function(key) {
            return CityField.variantsDelivery.points.list[key].RKO;
          });
        }
        delivery = {
          "id": id_delivery_points,
          "available": true,
          "active": true,
          "html_id": '#order_delivery_variant_id_' + id_delivery_points,
          "price": Math.min.apply(Math, arrayPrices) + (rko ? parseInt(Math.min.apply(Math, arrayRKO)) : 0),
          "fields_values": [],
          "selected": false,
          "description": null,
          "description_html": estimate,
          "is_external": false,
          "external_url": null,
          "external_data": {}
        };
        $('#order_delivery_variant_id_' + id_delivery_points).trigger('update:insales:delivery', delivery);
        $('.delivery_variants tr:nth-child(2)').find('select#pvz').append('<option value="" selected disabled>Выберите пункт выдачи</option>');
        return $.each(CityField.variantsDelivery.points.list, function(index, item) {
          price = (parseInt(item.price) + parseInt(rko ? item.RKO : 0)) + ' РУБ.';
          return $('.delivery_variants tr:nth-child(2)').find('select#pvz').append('<option value="' + item.name + ' ' + item.adress + ' ' + item.phone + '" data-adress="' + item.adress + '" data-rko="' + item.RKO + '"  data-code="' + item.code + '" data-price="' + item.price + '" data-min-estimate="' + item.min_estimate + '" data-max-estimate="' + item.max_estimate + '" data-worktime="' + item.workTime + '" data-phone="' + item.phone + '">' + item.name + ' - ' + price + '</option>');
        });
      }
    };


    /**
     * Обработка события нажатия на город в выпадающем списке
     */

    CityField.clickAutocompleteItem = function() {
      return CityField.autocompleteBlock.find('.address__autocomplete__item').click(function(e) {
        var contentType, data_name, id, name, selected;
        CityField.autocompleteBlock.hide();
        selected = this;
        contentType = 'city';
        id = selected.getAttribute('data-id');
        name = selected.getAttribute('data-full-name');
        if (selected.getAttribute('data-parent-full-name').length > 0) {
          name = name + ', ' + selected.getAttribute('data-parent-full-name');
        }
        data_name = selected.getAttribute('data-name');
        if (contentType === 'street') {
          name = selected.innerText || selected.textContent || '';
          data_name = selected.innerText || selected.textContent || '';
        }
        name = name.trim();
        $(selected).addClass('address__autocomplete__item--selected');
        $(CityField.field_id)[0].value = name.replace('г. ', '');
        CityField.kladr['city'] = $(selected).attr('data-name');
        if ($(selected).attr('data-parent-full-name').length > 0) {
          CityField.kladr['city_kladr'] = $(selected).attr('data-full-name') + ', ' + $(selected).attr('data-parent-full-name');
        } else {
          CityField.kladr['city_kladr'] = $(selected).attr('data-full-name');
        }
        CityField.kladr['index'] = $(selected).attr('data-zip');
        CityField.kladr['region'] = $(selected).attr('data-parent-value') ? $(selected).attr('data-parent-value') : CityField.kladr['city_kladr'];
        CityField.kladr['kladr_code'] = $(selected).attr('data-id');
        return CityField.saveKladr(CityField.kladr['city'], CityField.kladr['city_kladr'], CityField.kladr['index'], CityField.kladr['region'], CityField.kladr['kladr_code']);
      });
    };


    /**
     * Запись данных кладр в куки
     */

    CityField.saveKladr = function(city, kladr_city, index, region, code) {
      var d;
      d = new Date(new Date().getTime() + 60 * 60 * 1000);
      Cookies.set('customstreetwear_kladr_city', CityField.kladr['city'], {
        expires: d.toUTCString()
      });
      Cookies.set('customstreetwear_kladr_city_kladr', CityField.kladr['city_kladr'], {
        expires: d.toUTCString()
      });
      Cookies.set('customstreetwear_kladr_index', CityField.kladr['index'], {
        expires: d.toUTCString()
      });
      Cookies.set('customstreetwear_kladr_region', CityField.kladr['region'], {
        expires: d.toUTCString()
      });
      return Cookies.set('customstreetwear_kladr_code', CityField.kladr['kladr_code'], {
        expires: d.toUTCString()
      });
    };


    /**
     * Проверка способов оплаты
     */

    CityField.checkPaymentMethods = function() {
      return CityField.checkEnableDelivery();
    };


    /**
     * Валидация email адреса
     */

    CityField.isEmail = function(email) {
      var regex;
      regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
      return regex.test(email);
    };


    /**
     * Валидация полей оформления заказа
     */

    CityField.validate = function(object) {
      var errors, selectValue;
      object = object || false;
      errors = 0;
      if (object) {
        if ($(object).parent().parent().hasClass('input--required')) {
          if ($(object).attr('id') === 'client_phone') {
            setTimeout(function() {
              if ($(object).val() === '') {
                if ($(object).addClass('error')) {
                  return errors++;
                }
              }
            }, 200);
          } else if ($(object).attr('id') === 'client_email') {
            if (!CityField.isEmail($(object).val())) {
              if ($(object).addClass('error')) {
                errors++;
              }
            }
          } else {
            if ($(object).val() === '') {
              if ($(object).addClass('error')) {
                errors++;
              }
            }
          }
        }
        $('.input').each(function(i, e) {
          if ($(e).hasClass('input--required')) {
            if ($(object).parent().parent().offset().top === $(e).offset().top) {
              return false;
            } else {
              if ($(e).find('input:not([readonly])').eq(0).val() === '') {
                if ($(e).find('input').addClass('error')) {
                  errors++;
                }
              }
              if ($(e).find('input').attr('id') === 'client_email' && !CityField.isEmail($(e).find('input').val())) {
                if ($(e).find('input').addClass('error')) {
                  errors++;
                }
              }
              if ($(e).find('textarea').val() === '') {
                if ($(e).find('textarea').addClass('error')) {
                  return errors++;
                }
              }
            }
          }
        });
      } else {
        selectValue = false;
        if ($('select#pvz option:selected').length > 0) {
          if (($('select#pvz option:selected').val()).length === 0) {
            selectValue = true;
          }
        }
        if (selectValue && $('#order_delivery_variant_id_' + CityField.id_delivery_points).prop('checked')) {
          $('select#pvz').parent().addClass('error');
          errors++;
        } else {
          $('select#pvz').parent().removeClass('error');
        }
        $('.input').each(function(i, e) {
          if ($(e).hasClass('input--required')) {
            if ($(e).find('input:not([readonly])').eq(0).val() === '') {
              if ($(e).find('input').addClass('error')) {
                errors++;
              }
            }
            if ($(e).find('input').attr('id') === 'client_email' && !CityField.isEmail($(e).find('input').val())) {
              if ($(e).find('input').addClass('error')) {
                errors++;
              }
            }
            if ($(e).find('textarea').val() === '') {
              if ($(e).find('textarea').addClass('error')) {
                return errors++;
              }
            }
          }
        });
      }
      if (($('.delivery_variants').hasClass('loader') || $('.payment_variants').hasClass('loader')) && CityField.limit >= 0) {
        errors++;
      }
      if (errors > 0) {
        return false;
      } else {
        return true;
      }
    };


    /**
     * Лимит обработки получения доставки и оплаты
     */

    CityField.limiter = function() {
      return console.log('set limiter');
    };


    /**
     * Очистка данных кладр в куки
     */

    CityField.clearKladr = function() {
      Cookies.remove('customstreetwear_kladr_city');
      Cookies.remove('customstreetwear_kladr_city_kladr');
      Cookies.remove('customstreetwear_kladr_index');
      Cookies.remove('customstreetwear_kladr_region');
      return Cookies.remove('customstreetwear_kladr_code');
    };


    /**
     * Построение выпадающего списка с городами
     */

    CityField.buildVariants = function(data, query, searchContext) {
      return data.map(function(el) {
        var fullName, parent, result, type;
        fullName = el.name;
        type = void 0;
        if (el.type === 'Автономный округ') {
          type = 'autonomus';
        } else if (el.type === 'Область') {
          fullName += ' область';
          type = 'region';
        } else if (el.type === 'Город') {
          type = 'city';
          fullName = 'г. ' + fullName;
        } else if (el.type === 'Республика') {
          if (!fullName.match(/Республика/gi)) {
            fullName = 'Республика ' + fullName;
          }
          type = 'resp';
        } else {
          fullName = el.type + ' ' + fullName;
        }
        result = {
          id: el.id,
          name: el.name,
          'full-name': fullName,
          type: type,
          zip: el.zip,
          okato: el.okato
        };
        parent = {};
        if (el.parents && el.parents.length) {
          parent = el.parents.filter(function(parent) {
            return parent.contentType === 'region';
          })[0] || {};
        }
        result['parent-id'] = parent.id || 0;
        result['parent-type'] = parent.contentType || '';
        result['parent-value'] = parent.name || '';
        result['parent-full-name'] = (result['parent-value'] + ' ' + (parent.type || '')).trim();
        return result;
      }).map(function(el, index) {
        var foundIndex;
        var found;
        var foundIndex;
        var found;
        var attrs, className, e, error, found, foundIndex, fullName, inner, n, regExp;
        attrs = [];
        for (n in el) {
          if (el.hasOwnProperty(n)) {
            attrs.push('data-' + n + '="' + el[n] + '"');
          }
        }
        fullName = el['full-name'];
        inner = '';
        try {
          regExp = new RegExp(query, 'i');
          found = fullName.match(regExp);
          foundIndex = found ? found.index : fullName.length;
        } catch (error) {
          e = error;
          found = {
            index: 0,
            0: ''
          };
          foundIndex = 0;
        }
        inner += fullName.slice(0, foundIndex);
        if (foundIndex !== fullName.length) {
          inner += '<span class="address__autocomplete__item__highlight">' + found[0] + '</span>';
          inner += fullName.slice(found.index + found[0].length);
        }
        if (el['parent-full-name']) {
          inner += ', ' + el['parent-full-name'];
        }
        className = 'address__autocomplete__item';
        if (index === 0) {
          className += ' address__autocomplete__item--selected';
        }
        return '<div class="' + className + '" ' + attrs.join(' ') + '>' + inner.replace('г. ', '') + '</div>';
      }).join('');
    };

    return CityField;

  })();

  $order_form = $('#order_form');

  if ($order_form.length > 0) {
    city = new CityField('cc6ee94721ba7afe85ddb77f636ebcce', '16cb20407b4bbfd0ecf63ea2f25349e3', 5, 'shipping_address_city', 415531, 415532, 3224898, 435233, 344685, 359944, 310842, 3247644);
    city.init();
    $('#shipping_address_state').parent().parent().hide();
    $('#shipping_address_state option').remove();
    $(document).on('inited:insales:checkout:deliveries', function(e) {
      $(document).trigger('ready:insales:delivery');
      return false;
    });
    $(document).on('selected:insales:checkout:delivery', function(e) {
      return console.log('selected:insales:checkout:delivery');
    });
    $(document).on('updated:insales:checkout:delivery', function(e) {
      console.log('updated:insales:checkout:delivery');
      if (CityField.requestStatus === 1) {
        CityField.checkEnableDelivery();
        $('.delivery_variants').removeClass('loader');
        $('.delivery_variants .load').remove();
        CityField.checkPaymentMethods();
      }
    });
    $(document).on('selected:insales:delivery', function(e) {
      console.log('selected:insales:delivery');
      $('.payment_variants input[type="radio"]').eq(0).click();
      $('.payment_variants').addClass('loader');
      if ($('.payment_variants tbody .load').length === 0) {
        return $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
      }
    });
    $(document).on('updated:insales:payment', function(e) {
      $(document).trigger('selected:insales:payment');
      return setTimeout(function() {
        $('html.html_checkout .body.checkout #payment_gateways .total_price .fr').html($('html.html_checkout .body.checkout .set-sidebar #total_price').html());
        $('html.html_checkout .body.checkout #payment_gateways .total_price .fr span').remove();
        if (Math.abs(parseInt($('#summ_' + CityField.id_payment_online).attr('data-price'))) === 0) {
          $('#order_payment_gateway_id_' + CityField.id_payment_online).parent().parent().find('.price').removeClass('show');
        }
        if ($('.payment_variants .load').length > 0) {
          console.log('updated:insales:payment');
          if ($('#order_delivery_variant_id_' + CityField.id_delivery_post_calc).prop('checked')) {
            CityField.setRKO(CityField.variantsDeliveryPost.RKO, 'rko_post_calc');
          } else {
            $('.rko_post_calc').remove();
          }
          if ($('.payment_variants tbody').height() > 0) {
            if ($('.delivery_variants .load').length === 0) {
              $('.payment_variants').removeClass('loader');
              CityField.setSaleSidebar();
              $('.payment_variants .load').remove();
              $('#payment_gateways .rko').show();
            }
          } else {
            $('.payment_variants').addClass('loader');
            if ($('.payment_variants tbody .load').length === 0) {
              $('.payment_variants tbody').append('<tr class="load"><td></td></tr>');
            }
          }
        }
        return CityField.setSaleSidebar();
      }, 1000);
    });
    $(document).on('select:insales:payment', function(e) {
      return CityField.setSaleSidebar();
    });
    $(document).on('selected:insales:payment', function(e) {
      CityField.setSaleSidebar();
      setTimeout(function() {
        var descriptionDeliveryPost, payment;
        console.log('selected:insales:payment');
        if (Math.abs(parseInt($('#summ_' + CityField.id_payment_online_2).attr('data-price'))) > 0 && parseInt($('#summ_' + CityField.id_payment_online).attr('data-price')) === 0 && CityField.maxTotalPrice > CityField.order.total_price) {
          payment = {
            "id": CityField.id_payment_online,
            "available": true,
            "active": true,
            "html_id": '#order_payment_gateway_id_' + CityField.id_payment_online,
            "price": Math.floor($('#summ_' + CityField.id_payment_online_2).attr('data-price')),
            "fields_values": [],
            "selected": false,
            "description": null,
            "description_html": null,
            "is_external": false,
            "external_url": null,
            "external_data": {}
          };
          console.log('set payment');
          $('#order_payment_gateway_id_' + CityField.id_payment_online).trigger('update:insales:payment', payment);
          if ($('label[for="order_payment_gateway_id_' + CityField.id_payment_online + '"]').length > 0) {
            $('#order_payment_gateway_id_' + CityField.id_payment_online).parent().parent().find('td.name').find('.sale_description').remove();
            if (CityField.margin > 0) {
              $('#order_payment_gateway_id_' + CityField.id_payment_online).parent().parent().find('td.name').append('<div class="sale_description">Скидка при оплате онлайн ' + CityField.margin + '%</div>');
            }
          }
          $('#order_payment_gateway_id_' + CityField.id_payment_online).parent().parent().find('.price').addClass('show');
        }
        if ($('#order_delivery_variant_id_' + CityField.id_delivery_post_calc).prop('checked')) {
          if ($('#order_payment_gateway_id_' + CityField.id_payment_postcalc).prop('checked')) {
            descriptionDeliveryPost = $('#order_field_' + CityField.id_delivery_point_description).val();
            descriptionDeliveryPost += ', РКО: ' + CityField.variantsDeliveryPost.RKO + ' руб.';
            return $('#order_field_' + CityField.id_delivery_point_description).val(descriptionDeliveryPost);
          } else {
            descriptionDeliveryPost = 'Почта России ' + CityField.variantsDeliveryPost.deliveryType;
            return $('#order_field_' + CityField.id_delivery_point_description).val(descriptionDeliveryPost);
          }
        }
      }, 1000);
    });
    $('input, textarea, select').each(function(i, e) {
      return $(e).bind('blur.validate', function() {
        return CityField.validate(this);
      });
    });
    orderFormSubmit = function() {
      $order_form.find('input[type="submit"]#create_order').bind('click', function() {
        if (CityField.validate()) {
          return $order_form.submit();
        } else {
          $('input.error, textarea.error, select.error').eq(0).focus();
          if ($('input.error, textarea.error, select.error').eq(0).offset() !== void 0) {
            return $(window).scrollTop($('input.error, textarea.error, select.error').eq(0).offset().top - 40);
          }
        }
      });
      return $order_form.bind('submit', function() {
        var callbackSubmit, orderFormParams;
        if (CityField.validate()) {
          orderFormParams = $order_form.serializeArray();
          orderFormParams.forEach(function(e, i) {
            if (orderFormParams[i].name === 'shipping_address[city]') {
              return orderFormParams[i].value = orderFormParams[i].value.substr(0, orderFormParams[i].value.indexOf(','));
            }
          });
          if ($order_form.find('input[type="submit"]').val() !== 'Обработка...') {
            callbackSubmit = function() {
              return $.post($order_form.attr('action'), $order_form.serialize(), function(response, status, request) {
                var number, order_id, orig, orig_number, res;
                if (status === 'success') {
                  orig = response;
                  res = orig.substr(orig.indexOf('/orders/successful?id='), orig.length);
                  res = res.substr('/orders/successful?id='.length, res.indexOf(')') - 3);
                  res = res.replace(' ', '');
                  order_id = res.substr(0, res.indexOf(';') - 2);
                  if (order_id) {
                    orig_number = response;
                    number = orig_number.substring(orig_number.indexOf('<title>'), orig_number.indexOf('</title>')).replace(/\D/g, '');
                    $.post('http://82.196.3.195:8008/delivery_set.php', {
                      'id': number
                    }, function() {});
                    return setTimeout(function() {
                      location.href = '/orders/' + order_id;
                      return true;
                    }, 1000);
                  } else {
                    $order_form.unbind('submit').submit();
                    return true;
                  }
                }
              });
            };
            if ($('#order_payment_gateway_id_' + CityField.id_payment_online).prop('checked') && Math.abs(parseInt($('#summ_' + CityField.id_payment_online).attr('data-price'))) > 0) {
              $(document).on('updated:insales:payment selected:insales:payment', function(e) {
                return callbackSubmit();
              });
              $('#order_payment_gateway_id_' + CityField.id_payment_online_2).click();
            } else {
              callbackSubmit();
            }
            $order_form.find('input[type="submit"]').val('Обработка...');
          }
        } else {
          $order_form.find('input[type="submit"]').val('Оформление заказа');
        }
        return false;
      });
    };
    orderFormSubmit();
  }

}).call(this);

//# sourceMappingURL=calculator_shipping.js.map
